openapi: 3.0.0
info:
  title: Domain Name Checker API
  description: An API to check the availability of domain names.
  version: "1.0.0"
servers:
  - url: http://localhost:5000
paths:
  /check_domains:
    post:
      summary: Checks the availability of a list of domain names.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain_names:
                  type: array
                  items:
                    type: string
                  description: A list of domain names to check.
      responses:
        '200':
          description: A list of available domain names.
          content:
            application/json:
              schema:
                type: object
                properties:
                  available_domains:
                    type: array
                    items:
                      type: string
                    description: List of available domain names.
